version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
  open-pull-requests-limit: 10
  labels:
  - maintenance
  ignore:
  - dependency-name: Spectre.Console
    versions:
    - 0.37.0
    - 0.38.0
  - dependency-name: Microsoft.VisualStudio.Threading.Analyzers
    versions:
    - 16.9.54
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: coverlet.collector
    versions:
    - 3.0.2
  - dependency-name: Moq
    versions:
    - 4.16.0
  - dependency-name: MinVer
    versions:
    - 2.4.0
