// <auto-generated />
using System;
using DataTableEfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataTableEfCore.Migrations
{
    [DbContext(typeof(PersonContext))]
    partial class PersonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("DataTableEfCore.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.ToTable("Composers");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            Age = 65,
                            FirstName = "Sebastian",
                            LastName = "Bach"
                        },
                        new
                        {
                            PersonId = 2,
                            Age = 56,
                            FirstName = "Ludwig",
                            LastName = "Beethoven"
                        },
                        new
                        {
                            PersonId = 3,
                            Age = 31,
                            FirstName = "Franz",
                            LastName = "Schubert"
                        },
                        new
                        {
                            PersonId = 4,
                            Age = 77,
                            FirstName = "Joseph",
                            LastName = "Haydn"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
